services:
  four2six:
    image: ghcr.io/muckelba/four2six:latest
    restart: unless-stopped
    networks:
      - default
    env_file:
      - .env
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./config:/app/config  

networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8::/64
